[general]
static=yes
writeprotect=no

[from-webrtc]
exten => _X.,1,NoOp(Outgoing call from browser: ${EXTEN})
 same => n,Stasis(callapp,outbound)
 same => n,Hangup()

[from-dinstar]
exten => _.,1,NoOp(Incoming from Dinstar: ${CALLERID(num)})
 same => n,Stasis(callapp,inbound)
 same => n,Hangup()

exten => s,1,NoOp(Incoming from Dinstar no-number)
 same => n,Stasis(callapp,inbound)
 same => n,Hangup()
