-- -- ─────────────────────────────────────────────────────────────────────────────
-- --  Asterisk PJSIP Realtime Tables
-- --  These let Asterisk read ALL SIP endpoint/auth/aor config from MySQL.
-- --  After running this you NEVER edit pjsip.conf for employees or gateways again.
-- --
-- --  Run once:
-- --    mysql -u root -p callcenter < db/asterisk-realtime-tables.sql
-- -- ─────────────────────────────────────────────────────────────────────────────

-- -- Endpoints (one row per SIP peer)
-- CREATE TABLE IF NOT EXISTS ps_endpoints (
--   id                          VARCHAR(40)  NOT NULL,
--   transport                   VARCHAR(40)  NULL,
--   aors                        VARCHAR(200) NULL,
--   auth                        VARCHAR(200) NULL,
--   context                     VARCHAR(40)  NULL,
--   disallow                    VARCHAR(200) NULL,
--   allow                       VARCHAR(200) NULL,
--   direct_media                VARCHAR(3)   NULL DEFAULT 'yes',
--   connected_line_method        VARCHAR(40)  NULL,
--   direct_media_method          VARCHAR(40)  NULL,
--   direct_media_glare_mitigation VARCHAR(40) NULL,
--   disable_direct_media_on_nat  VARCHAR(3)  NULL,
--   dtmf_mode                   VARCHAR(40)  NULL,
--   external_media_address       VARCHAR(40)  NULL,
--   force_rport                  VARCHAR(3)  NULL,
--   ice_support                  VARCHAR(3)  NULL,
--   identify_by                  VARCHAR(40)  NULL,
--   mailboxes                    VARCHAR(40)  NULL,
--   moh_suggest                  VARCHAR(40)  NULL,
--   outbound_auth                VARCHAR(40)  NULL,
--   outbound_proxy               VARCHAR(40)  NULL,
--   rewrite_contact              VARCHAR(3)  NULL,
--   rtp_ipv6                     VARCHAR(3)  NULL,
--   rtp_symmetric                VARCHAR(3)  NULL,
--   send_pai                     VARCHAR(3)  NULL,
--   use_avpf                     VARCHAR(3)  NULL,
--   media_encryption              VARCHAR(40) NULL,
--   inband_progress               VARCHAR(3)  NULL,
--   call_group                    VARCHAR(40) NULL,
--   pickup_group                  VARCHAR(40) NULL,
--   named_call_group              VARCHAR(40) NULL,
--   named_pickup_group            VARCHAR(40) NULL,
--   device_state_busy_at          INT        NULL,
--   t38_udptl                     VARCHAR(3)  NULL,
--   t38_udptl_ec                  VARCHAR(40) NULL,
--   t38_udptl_maxdatagram         INT        NULL,
--   t38_udptl_nat                 VARCHAR(3)  NULL,
--   t38_udptl_ipv6                VARCHAR(3)  NULL,
--   tone_zone                     VARCHAR(40) NULL,
--   language                      VARCHAR(40) NULL,
--   one_touch_recording            VARCHAR(3)  NULL,
--   record_on_feature              VARCHAR(40) NULL,
--   record_off_feature             VARCHAR(40) NULL,
--   rtp_engine                    VARCHAR(40) NULL,
--   allow_transfer                 VARCHAR(3)  NULL,
--   sdp_owner                     VARCHAR(40) NULL,
--   sdp_session                   VARCHAR(40) NULL,
--   tos_audio                     VARCHAR(10) NULL,
--   tos_video                     VARCHAR(10) NULL,
--   cos_audio                     INT        NULL,
--   cos_video                     INT        NULL,
--   sub_min_expiry                 INT        NULL,
--   from_domain                   VARCHAR(40) NULL,
--   from_user                     VARCHAR(40) NULL,
--   mwi_from_user                 VARCHAR(40) NULL,
--   dtls_verify                   VARCHAR(40) NULL,
--   dtls_rekey                    VARCHAR(40) NULL,
--   dtls_cert_file                VARCHAR(200) NULL,
--   dtls_private_key              VARCHAR(200) NULL,
--   dtls_cipher                   VARCHAR(200) NULL,
--   dtls_ca_file                  VARCHAR(200) NULL,
--   dtls_ca_path                  VARCHAR(200) NULL,
--   dtls_setup                    VARCHAR(40) NULL,
--   dtls_fingerprint              VARCHAR(40) NULL,
--   srtp_tag_32                   VARCHAR(3)  NULL,
--   media_address                 VARCHAR(40) NULL,
--   redirect_method               VARCHAR(40) NULL,
--   set_var                       VARCHAR(200) NULL,
--   `100rel`                      VARCHAR(40) NULL,
--   preferred_codec_only          VARCHAR(3)  NULL,
--   asymmetric_rtp_codec          VARCHAR(3)  NULL,
--   rtcp_mux                      VARCHAR(3)  NULL,
--   allow_overlap                 VARCHAR(3)  NULL,
--   refer_blind_progress          VARCHAR(3)  NULL,
--   notify_early_inuse_ringing    VARCHAR(3)  NULL,
--   max_audio_streams             INT        NULL,
--   max_video_streams             INT        NULL,
--   bundle                        VARCHAR(3)  NULL,
--   webrtc                        VARCHAR(3)  NULL,
--   incoming_mwi_mailbox          VARCHAR(40) NULL,
--   follow_early_media_fork       VARCHAR(3)  NULL,
--   accept_multiple_sdp_answers   VARCHAR(3)  NULL,
--   suppress_q850_reason_headers  VARCHAR(3)  NULL,
--   trust_connected_line          VARCHAR(3)  NULL,
--   send_connected_line           VARCHAR(3)  NULL,
--   ignore_183_without_sdp        VARCHAR(3)  NULL,
--   codec_prefs_incoming_offer    VARCHAR(128) NULL,
--   codec_prefs_outgoing_offer    VARCHAR(128) NULL,
--   codec_prefs_incoming_answer   VARCHAR(128) NULL,
--   codec_prefs_outgoing_answer   VARCHAR(128) NULL,
--   stir_shaken                   VARCHAR(3)  NULL,
--   dtls_auto_generate_cert       VARCHAR(3)  NULL,
--   UNIQUE KEY id (id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -- Authentication objects
-- CREATE TABLE IF NOT EXISTS ps_auths (
--   id              VARCHAR(40)  NOT NULL,
--   auth_type       VARCHAR(40)  NULL,
--   nonce_lifetime  INT          NULL,
--   md5_cred        VARCHAR(40)  NULL,
--   password        VARCHAR(80)  NULL,
--   realm           VARCHAR(40)  NULL,
--   username        VARCHAR(40)  NULL,
--   UNIQUE KEY id (id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -- Address of Record objects
-- CREATE TABLE IF NOT EXISTS ps_aors (
--   id                          VARCHAR(40)  NOT NULL,
--   contact                     VARCHAR(255) NULL,
--   default_expiry              INT          NULL,
--   mailboxes                   VARCHAR(80)  NULL,
--   max_contacts                INT          NULL,
--   minimum_expiry              INT          NULL,
--   remove_existing             VARCHAR(3)   NULL,
--   qualify_frequency           INT          NULL,
--   authenticate_qualify        VARCHAR(3)   NULL,
--   maximum_expiry              INT          NULL,
--   outbound_proxy              VARCHAR(40)  NULL,
--   support_path                VARCHAR(3)   NULL,
--   qualify_timeout             FLOAT        NULL,
--   voicemail_extension         VARCHAR(40)  NULL,
--   UNIQUE KEY id (id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -- Endpoint identification (match by IP for gateways)
-- CREATE TABLE IF NOT EXISTS ps_endpoint_id_ips (
--   id       VARCHAR(40)  NOT NULL,
--   endpoint VARCHAR(40)  NOT NULL,
--   `match`  VARCHAR(80)  NOT NULL,
--   UNIQUE KEY id (id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
