;
; Asterisk configuration file
;
; Module Loader configuration file
;

; /etc/asterisk/modules.conf
[modules]
autoload=yes

; Force-load only what we specifically need for WebRTC
load => res_http_websocket.so
load => res_pjsip.so
load => res_pjsip_session.so
load => chan_pjsip.so
load => res_pjsip_transport_websocket.so
load => res_config_mysql.so
load => app_confbridge.so
load => res_redis.so
; Optional: Opus codec if present
load => codec_opus.so

; Keep these disabled (examples)
noload => pbx_gtkconsole.so
noload => pbx_kdeconsole.so
noload => app_intercom.so
noload => chan_modem.so
noload => chan_modem_aopen.so
noload => chan_modem_bestdata.so
noload => chan_modem_i4l.so
noload => chan_alsa.so
noload => chan_console.so
noload => chan_oss.so
noload => cdr_sqlite.so
noload => app_directory_odbc.so
noload => res_config_odbc.so
noload => res_config_pgsql.so
noload => chan_sip.so
