; /etc/asterisk/queues.conf

[general]
persistentmembers = no
shared_lastcall = yes
autofill = yes
monitor-type = MixMonitor

[campaign_queue_template](!)
strategy = leastrecent
timeout = 30
wrapuptime = 5
ringinuse = no
autopause = no
maxlen = 0
announce-frequency = 0
retry = 5
queue-callswaiting = no
eventwhencalled = yes  ; Enable queue events for debugging
eventmemberstatus = yes


